---
AWSTemplateFormatVersion: 2010-09-09
Description: Zack olivier | This template deploy a VPC
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: 'true'
      Tags:
        - Key: name
          Value: zackVPC
